### PR TITLE
update contributing info

### PR DESCRIPTION
**Pull request by davidgcameron**

### CODE REVIEW

**Review by floridop — APPROVED** [review]
looks good to me! how about porting to gitlab maybe using this:
https://help.github.com/en/articles/checking-out-pull-requests-locally

**Review by floridop — APPROVED** [review]
I am ok with the latest change

**Comment by floridop** [comment]
I will try adding this via gitlab now

**Comment by floridop** [comment]
@davidgcameron the file has changed a lot since the submission, when i tried to do the merges offline the diff shows much more stuff, could you try to merge in your branch before merging here?

**Comment by davidgcameron** [comment]
Let me close this old one and make a new one to test the workflow.

**Pull request closed without merging**
